import { describe, it, expect, beforeEach } from "vitest";

import { defineEnv, str, num, port, oneOf, EnvValidationError } from "../src/index";
import { renderEnvExample } from "../src/cli/example";
import { renderDocs } from "../src/cli/docs";
import { clearRegistry } from "../src/registry";

/**
 * Snapshot coverage for the human-facing output (issue #8): the boot-time
 * failure report, the generated `.env.example`, and the `docs` table. These
 * lock the exact rendered text so an accidental formatting change is caught in
 * review instead of shipping. A representative schema exercises descriptions,
 * defaults, secrets, enums, optionals, and mixed failure kinds.
 */

// A fresh schema per call — validators are stateful, don't share across tests.
const schema = () => ({
  NODE_ENV: oneOf(["development", "production", "test"]).default("development").desc("Runtime mode"),
  PORT: port().default(3000),
  DATABASE_URL: str().desc("Postgres connection string"),
  STRIPE_KEY: str().secret().startsWith("sk_"),
  LOG_LEVEL: oneOf(["debug", "info", "warn", "error"]).optional(),
  MAX_RETRIES: num().int().default(3),
});

beforeEach(() => {
  clearRegistry();
  delete process.env.PRAHARI_SKIP_VALIDATION;
});

describe("snapshot", () => {
  it("boot-time failure report (with redaction)", () => {
    let message = "";
    try {
      defineEnv(schema(), {
        // DATABASE_URL missing, PORT/STRIPE_KEY/MAX_RETRIES invalid;
        // NODE_ENV + LOG_LEVEL are fine (default / optional).
        source: { PORT: "not-a-port", STRIPE_KEY: "pk_wrong", MAX_RETRIES: "1.5" },
      });
    } catch (e) {
      message = (e as EnvValidationError).message;
    }
    expect(message).toMatchInlineSnapshot(`
      "prahari: 4 environment variables failed validation

        ✗ PORT          (port)    must be a number  received: "not-a-port"
        ✗ DATABASE_URL  (string)  is required but was not set
        ✗ STRIPE_KEY    (string)  must start with "sk_"  received: ***
        ✗ MAX_RETRIES   (number)  must be an integer  received: "1.5"
      "
    `);
  });

  it("generated .env.example", () => {
    expect(renderEnvExample(schema())).toMatchInlineSnapshot(`
      "# Generated by prahari — edits may be overwritten.
      # Regenerate: \`prahari example\`   ·   Check drift: \`prahari sync\`

      # Runtime mode
      # (has default, enum, one of: development | production | test)
      NODE_ENV=development

      # (has default, port)
      PORT=3000

      # Postgres connection string
      # (required, string)
      DATABASE_URL=

      # (required, secret, string)
      STRIPE_KEY=

      # (optional, enum, one of: debug | info | warn | error)
      LOG_LEVEL=debug

      # (has default, number)
      MAX_RETRIES=3
      "
    `);
  });

  it("docs Markdown table", () => {
    expect(renderDocs(schema())).toMatchInlineSnapshot(`
      "| Variable | Type | Required | Default | Description |
      | --- | --- | --- | --- | --- |
      | \`NODE_ENV\` | \`development\` \\| \`production\` \\| \`test\` | no | \`development\` | Runtime mode |
      | \`PORT\` | port | no | \`3000\` |  |
      | \`DATABASE_URL\` | string | yes | — | Postgres connection string |
      | \`STRIPE_KEY\` | string (secret) | yes | — |  |
      | \`LOG_LEVEL\` | \`debug\` \\| \`info\` \\| \`warn\` \\| \`error\` | no | — |  |
      | \`MAX_RETRIES\` | number | no | \`3\` |  |
      "
    `);
  });
});
