/**
 * `prahari example` — render a `.env.example` from the schema.
 *
 * Pure renderer (unit-testable); the command wrapper does the file IO.
 */

import { describeField, type EnvSchema, type FieldDescriptor } from "../validators.js";

function tagsFor(d: FieldDescriptor): string {
  const tags: string[] = [];
  // A bare Standard Schema exposes no optional/default info — don't guess.
  if (!d.opaque) {
    tags.push(d.optional ? "optional" : d.hasDefault ? "has default" : "required");
  }
  if (d.secret) tags.push("secret");
  tags.push(d.opaque ? `${d.typeName} (standard-schema)` : d.typeName);
  if (d.enumValues) tags.push(`one of: ${d.enumValues.join(" | ")}`);
  return tags.join(", ");
}

/** Produce the full text of a `.env.example` file for a schema. */
export function renderEnvExample(schema: EnvSchema): string {
  const lines: string[] = [
    "# Generated by prahari — edits may be overwritten.",
    "# Regenerate: `prahari example`   ·   Check drift: `prahari sync`",
    "",
  ];

  for (const key of Object.keys(schema)) {
    const d = describeField(schema[key]!);
    if (d.description) lines.push(`# ${d.description}`);
    lines.push(`# (${tagsFor(d)})`);
    // Never write a real example for secrets — leave the value blank.
    const value = d.secret ? "" : d.exampleValue();
    lines.push(`${key}=${value}`);
    lines.push("");
  }

  // Collapse the trailing blank lines to exactly one newline.
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}
