/**
 * `envguard example` — render a `.env.example` from the schema.
 *
 * Pure renderer (unit-testable); the command wrapper does the file IO.
 */

import type { EnvSchema, Validator } from "../validators.js";

function tagsFor(v: Validator<unknown>): string {
  const tags: string[] = [];
  tags.push(v.meta.optional ? "optional" : v.meta.hasDefault ? "has default" : "required");
  if (v.meta.secret) tags.push("secret");
  tags.push(v.meta.typeName);
  if (v.meta.enumValues) tags.push(`one of: ${v.meta.enumValues.join(" | ")}`);
  return tags.join(", ");
}

/** Produce the full text of a `.env.example` file for a schema. */
export function renderEnvExample(schema: EnvSchema): string {
  const lines: string[] = [
    "# Generated by envguard — edits may be overwritten.",
    "# Regenerate: `envguard example`   ·   Check drift: `envguard sync`",
    "",
  ];

  for (const key of Object.keys(schema)) {
    const v = schema[key] as Validator<unknown>;
    if (v.meta.description) lines.push(`# ${v.meta.description}`);
    lines.push(`# (${tagsFor(v)})`);
    // Never write a real example for secrets — leave the value blank.
    const value = v.meta.secret ? "" : v.exampleValue();
    lines.push(`${key}=${value}`);
    lines.push("");
  }

  // Collapse the trailing blank lines to exactly one newline.
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}
